-- Drop existing tables if they exist
DROP TABLE IF EXISTS invoice_items;
DROP TABLE IF EXISTS invoices;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS loan_payments;
DROP TABLE IF EXISTS loans;
DROP TABLE IF EXISTS cv_store;
DROP TABLE IF EXISTS vault_store;

-- 1. Create 'products' table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL DEFAULT 0,
  stock INTEGER NOT NULL DEFAULT 0,
  is_print BOOLEAN DEFAULT false,
  is_blocked BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert some default products (including the Quick Print ones)
INSERT INTO products (name, price, stock, is_print) VALUES 
('A4 Paper Bundle', 350.00, 50, false),
('Log Print (B&W)', 5.00, 10000, true),
('Log Print (Color)', 15.00, 5000, true);

-- 2. Create 'invoices' table
CREATE TABLE invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  total_amount NUMERIC NOT NULL,
  discount NUMERIC DEFAULT 0,
  customer_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create 'invoice_items' table
CREATE TABLE invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  quantity INTEGER NOT NULL,
  price_at_time NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create 'loans' table
CREATE TABLE loans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_type TEXT DEFAULT 'lent',
  person_name TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  amount_paid NUMERIC DEFAULT 0,
  due_date TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Create 'loan_payments' table
CREATE TABLE loan_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id BIGINT REFERENCES loans(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  date TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Create 'cv_store' table
CREATE TABLE cv_store (
  id TEXT PRIMARY KEY,
  user_id UUID,
  cv_data JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Create 'vault_store' table
CREATE TABLE vault_store (
  device_id TEXT PRIMARY KEY,
  encrypted_data TEXT,
  salt TEXT,
  iv TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- DISABLE ROW LEVEL SECURITY (RLS) FOR DEMO / ANONYMOUS ACCESS
-- Since this is a demo/portfolio application that bypasses Supabase Auth,
-- we must disable RLS so that the Anon API Key can read and write freely.
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE loans DISABLE ROW LEVEL SECURITY;
ALTER TABLE loan_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE cv_store DISABLE ROW LEVEL SECURITY;
ALTER TABLE vault_store DISABLE ROW LEVEL SECURITY;
