-- Create products table
CREATE TABLE products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  price numeric NOT NULL DEFAULT 0,
  stock integer NOT NULL DEFAULT 0,
  is_print boolean DEFAULT false,
  is_blocked boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert initial dummy data
INSERT INTO products (name, price, stock, is_print) VALUES
  ('A4 Print (B&W)', 2, 5000, true),
  ('A4 Print (Color)', 10, 2000, true),
  ('Notebook', 45, 100, false),
  ('Blue Pen', 10, 250, false),
  ('Pencil', 5, 300, false),
  ('Watercolor Set', 120, 20, false);

-- Create invoices table
CREATE TABLE invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  total_amount numeric NOT NULL DEFAULT 0,
  discount numeric DEFAULT 0,
  customer_name text DEFAULT 'Walk-in Customer',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create invoice_items table
CREATE TABLE invoice_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint REFERENCES invoices(id) ON DELETE CASCADE,
  product_id bigint REFERENCES products(id),
  quantity integer NOT NULL,
  price_at_time numeric NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create loans table
CREATE TABLE loans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_type text NOT NULL CHECK (loan_type IN ('borrowed', 'lent')),
  person_name text NOT NULL,
  amount numeric NOT NULL,
  amount_paid numeric DEFAULT 0,
  interest_rate numeric DEFAULT 0,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'settled')),
  due_date date,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create loan_payments table
CREATE TABLE loan_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id bigint REFERENCES loans(id) ON DELETE CASCADE,
  amount numeric NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security (RLS)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE loans ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public access (for demo purposes)
-- Note: In a production app, you would restrict this to authenticated users
CREATE POLICY "Enable read access for all users" ON products FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON products FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON products FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON products FOR DELETE USING (true);

CREATE POLICY "Enable read access for all users" ON invoices FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON invoices FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON invoice_items FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON invoice_items FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable all actions for public loans" ON loans FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE loan_payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all actions for public loan_payments" ON loan_payments FOR ALL USING (true) WITH CHECK (true);
